#!/bin/bash

function show {
  clear
  figlet -w 120 $1
  read
}

git co master
show "the rails backlash"
show "#lolrails"
show "slow tests"
show "what's the problem?"
show "depot app"
bash --login
show "depot rspec'd"
git co with_rspec  
bash --login
show "lose the rake"
bash --login
show "fast tests"
git co fast_tests
bash --login
show "a step too far?"
show "brittle tests"
show "require active_record"
git co explicit_require
bash --login
show "do extract class"
show "do write less tests"
show "Objects on Rails"
show "questions?"

